solves 6
jchancoding/curriculum pull request #6
Opened 2018-01-28 00:32 UTC by jchancoding

2018-01-30 04:56 UTC, songz commented on curriculum/js1/6.js
> +    return console.log(sum);
don't console.log. return result.

2018-01-30 04:57 UTC, songz requested changes

2018-01-30 04:57 UTC, songz commented on curriculum/js1/6.js
> +solution(10);
don't write tests in your solution

2018-02-11 00:17 UTC, jchancoding commented
Solves 6 and passes test

2018-02-11 03:23 UTC, songz approved these changes

2018-02-11 03:36 UTC, merged